### ISSUE TITLE
[REFACTOR] 부스 서비스 예약 필드 추가

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#167]
## Description

- 부스 서비스 예약 등록할 때 서비스명, 이미지 가격을 추가로 입력하게 합니다.
## TODO

- [ ] 엔티티에 필드 추가
- [ ] db에 칼럼 추가
- [ ] 받아온 데이터 저장
