### ISSUE TITLE
[FEAT] 부스 예약 상태 변경 기능

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#204]
## Description

- 부스 관리자가 예약을 승인 혹은 거절하는 기능을 구현합니다.
## TODO

- [ ] 부스 예약 상세 id를 통해 객체 조회
- [ ] 예약 상태 변경 조건을 통한 상태 변경
- [ ] 변경 상태 저장
