### ISSUE TITLE
[REFACTOR] PageRequest 생성 메서드 Util 서비스로 분리

### ISSUE THREAD

**Issue by muncool39** [Project-OpenBook/openbook-server#210]
## Description

search 기능 사용시의 PageRequest 를 생성하는 기능을 util 로 사용할 수 있도록 변경합니다.

## TODO

- [ ] util 로 사용할 수 있도록 분리
- [ ] 행사 검색 기능 수정
- [ ] 부스 검색 기능 수정

## Additional context

util 이 아니더라도 둘이 동일하게 사용할 수 있도록 하자
