### ISSUE TITLE
[FEAT] 부스 정보 수정 기능

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#238]
## Description

- 부스 관리자가 본인의 부스의 기본 정보를 수정하는 API 를 개발할 예정입니다.
## TODO

- [x] 수정할 데이터 응답 받는 request 추가
- [x] 수정 권한 확인
- [x] 수정할 부스 id 찾아서 데이터 수정
