### ISSUE TITLE
[FEAT] 부스 공지 수정 기능

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#253]
## Description

- 등록된 부스 공지를 수정하는 기능입니다.
## TODO

- [ ] patch API 작성
- [ ] 수정 요청 받을  request 클래스 추가
- [ ] 수정 dto 추가
