### ISSUE TITLE
[FEAT] 부스 공지 삭제 기능

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#267]
## Description

- 부스 관리자가 자신의 부스를 삭제하는 기능을 개발합니다.
## TODO

- [x] 삭제할 부스 id를 받아온다.
- [x] 삭제할 부스가 로그인한 유저의 부스인지 확인한다.
- [x] id를 통해 객체를 삭제한다.
