### ISSUE TITLE
[FEAT] 예약 수정하는 API

### ISSUE THREAD

**Issue by gitseoyeon** [Project-OpenBook/openbook-server#285]
## Description

부스에 등록된 예약 정보를 수정하는 기능입니다.
각각의 예약 정보를 삭제하고 추가할 수 있습니다.

## TODO

- [x] 수정할 데이터를 담을 request 클래스 추가
- [x] 요청된 데이터 값이 수정 조건에 맞는지 판별
- [x] 엔티티에 update 메소드 추가
