### ISSUE TITLE
[REFACTOR] error code 를 사용하도록 변경

### ISSUE THREAD

**Issue by muncool39** [Project-OpenBook/openbook-server#66]
## Description

상태 코드-에러 메세지의 한 쌍이 저장된 에러 코드를 정의해
동일한 상황일 경우 해당 에러 코드를 사용하도록 리팩토링

## TODO

- [x] 에러 코드 클래스 추가
- [x] 기존 openbook exception 수정
- [x] 기존 에러 반환 코드들 수정

## Additional context
- #65 내용 포함
