### ISSUE TITLE
[FEAT] 알림 생성 기능

### ISSUE THREAD

**Issue by muncool39** [Project-OpenBook/openbook-server#73]
## Description

사용자의 동작에 따른 알림 생성 기능을 추가

## TODO

- [x] 메서드
- [x] 행사 등록 요청
- [x] 행사 승인 / 거절
- [x] 부스 등록 요청
- [x] 부스 승인 / 거절
